### ISSUE TITLE
error invalid number of arguments ANN.PY

### ISSUE THREAD

**Issue by leodsti** [ahmedfgad/NeuralGenetic#1]
Hi :)

Thank you for that work!
I tried to clone and run it, however, I am getting the following error :

Generation :  0
Traceback (most recent call last):
  File "Example_GA_ANN.py", line 64, in <module>
    activation="sigmoid")
  File "/MacLeo/NeuralGenetic/ANN.py", line 31, in fitness
    accuracy[sol_idx], _ = predict_outputs(curr_sol_mat, data_inputs, data_outputs, activation=activation)
  File "/MacLeo/NeuralGenetic/ANN.py", line 16, in predict_outputs
    r1 = numpy.matmul(a=r1, b=curr_weights)
ValueError: invalid number of arguments

Any ideas?

Thanks for the help !

Regards

**Comment by leodsti** [comment]
I solved my issue by deleting the name of the parameters "a" and "b".

**Comment by ahmedfgad** [comment]
Glad you find the solution :)
