### ISSUE TITLE
New population

### ISSUE THREAD

**Issue by adilahrashid** [ahmedfgad/NeuralGenetic#4]
Hi Ahmed!
I would like to know, why the new population created based on lines 88-90 is based on parents+offspring?
What is the rationale? Why isn't offspring alone?

**Comment by ahmedfgad** [comment]
Hi,
I highlighted the reason for doing that in my tutorial titled [Genetic Algorithm Implementation in Python](https://www.linkedin.com/pulse/genetic-algorithm-implementation-python-ahmed-gad). It is available at these links:
- https://www.linkedin.com/pulse/genetic-algorithm-implementation-python-ahmed-gad
- https://www.kdnuggets.com/2018/07/genetic-algorithm-implementation-python.html
- https://towardsdatascience.com/genetic-algorithm-implementation-in-python-5ab67bb124a6

Here is the part in which I explained the reason.
> Note that GA is a random-based optimization technique. It tries to enhance the current solutions by applying some random changes to them. Because such changes are random, we are not sure that they will produce better solutions. For such reason, it is preferred to keep the previous best solutions (parents) in the new population. In the worst case when all the new offspring are worse than such parents, we will continue using such parents. As a result, we guarantee that the new generation will at least preserve the previous good results and will not go worse. 

If you know Arabic, then you can watch this video [بالعربي Genetic Algorithm (GA) Optimization - Step by Step Example with Python Implementation](https://www.youtube.com/watch?v=sjddXIc_B20). 

Wish to find these resources helpful.

Ready to receive from you again.
