### ISSUE TITLE
Can PyGAD be used for solving any PDE?

### ISSUE THREAD

**Issue by dapratama** [ahmedfgad/NeuralGenetic#5]
Hello,

I have a project for solving PDE using Neural Networks and I interest for using PyGAD. Can PyGAD be used for solving PDE?

Thank you very much

**Comment by ahmedfgad** [comment]
Hello,

Yes you can use PyGAD for this task. To use PyGAD, then the most important thing to do is to build the appropriate fitness function to measure the quality of the solutions. 

In case you would like further assistance, please let me know.

Thanks.
